#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:55 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/administrating_record_company_role"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::AdministratingRecordCompanyWithReference < Element
  include ROXML


  xml_name "ns1:AdministratingRecordCompanyWithReference"

      xml_accessor :record_company_party_reference, :from => "RecordCompanyPartyReference", :required => true
      xml_accessor :role, :as => DDEX::ERN::V41::AdministratingRecordCompanyRole, :from => "Role", :required => true


  

end

end end end
