#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:55 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/contributor"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::Character < Element
  include ROXML


  xml_name "ns1:Character"

      xml_accessor :character_party_reference, :from => "CharacterPartyReference", :required => true
      xml_accessor :performer, :as => DDEX::ERN::V41::Contributor, :from => "Performer", :required => false


  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  

end

end end end
