#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:55 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::DealResourceReferenceList < Element
  include ROXML


  xml_name "ns1:DealResourceReferenceList"

      xml_accessor :deal_resource_references, :as => [], :from => "DealResourceReference", :required => true


  

end

end end end
