#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:55 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/bit_rate"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::DealTermsTechnicalInstantiation < Element
  include ROXML


  xml_name "ns1:DealTermsTechnicalInstantiation"

      xml_accessor :video_definition_type, :from => "VideoDefinitionType", :required => false
      xml_accessor :coding_type, :from => "CodingType", :required => false
      xml_accessor :bit_rate, :as => DDEX::ERN::V41::BitRate, :from => "BitRate", :required => false


  

end

end end end
