#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:56 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/hash_sum_algorithm_type"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::DetailedHashSum < Element
  include ROXML


  xml_name "ns1:DetailedHashSum"

      xml_accessor :algorithm, :as => DDEX::ERN::V41::HashSumAlgorithmType, :from => "Algorithm", :required => true
      xml_accessor :version, :from => "Version", :required => false
      xml_accessor :parameter, :from => "Parameter", :required => false
      xml_accessor :data_type, :from => "DataType", :required => false
      xml_accessor :hash_sum_value, :from => "HashSumValue", :required => true


  

end

end end end
