#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:56 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"


module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::DisplaySubTitle < Element
  include ROXML


  xml_name "ns1:DisplaySubTitle"


    xml_accessor :value, :from => ".", :required => false

  

      xml_accessor :sequence_number, :as => Integer, :from => "@SequenceNumber", :required => false
    
  
      xml_accessor :displayed_in_title?, :from => "@IsDisplayedInTitle", :required => false
    
  
      xml_accessor :sub_title_type, :from => "@SubTitleType", :required => false
    
  

end

end end end
