#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:56 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/message_audit_trail_event"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::MessageAuditTrail < Element
  include ROXML


  xml_name "ns1:MessageAuditTrail"

      xml_accessor :message_audit_trail_events, :as => [DDEX::ERN::V41::MessageAuditTrailEvent], :from => "MessageAuditTrailEvent", :required => true


  

end

end end end
