#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:56 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/messaging_party_without_code"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::MessageAuditTrailEvent < Element
  include ROXML


  xml_name "ns1:MessageAuditTrailEvent"

      xml_accessor :messaging_party_descriptor, :as => DDEX::ERN::V41::MessagingPartyWithoutCode, :from => "MessagingPartyDescriptor", :required => true
      xml_accessor :date_time, :as => DateTime, :from => "DateTime", :required => true


  

end

end end end
