#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:57 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/price"
require "ddex/ern/v41/price_type"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::PriceInformationWithType < Element
  include ROXML


  xml_name "ns1:PriceInformationWithType"

      xml_accessor :price_code, :as => DDEX::ERN::V41::PriceType, :from => "PriceCode", :required => false
      xml_accessor :wholesale_price_per_unit, :as => DDEX::ERN::V41::Price, :from => "WholesalePricePerUnit", :required => false
      xml_accessor :bulk_order_wholesale_price_per_unit, :as => DDEX::ERN::V41::Price, :from => "BulkOrderWholesalePricePerUnit", :required => false
      xml_accessor :suggested_retail_price, :as => DDEX::ERN::V41::Price, :from => "SuggestedRetailPrice", :required => false


  
      xml_accessor :price_type, :from => "@PriceType", :required => false
    
  

end

end end end
