#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:57 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/release_id"
require "ddex/ern/v41/timing"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::RelatedResource < Element
  include ROXML


  xml_name "ns1:RelatedResource"

      xml_accessor :resource_relationship_type, :from => "ResourceRelationshipType", :required => true
      xml_accessor :release_id, :as => DDEX::ERN::V41::ReleaseId, :from => "ReleaseId", :required => false
      xml_accessor :resource_related_resource_reference, :from => "ResourceRelatedResourceReference", :required => false
      xml_accessor :timings, :as => [DDEX::ERN::V41::Timing], :from => "Timing", :required => false


  

end

end end end
