#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:57 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/deal"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::ReleaseDeal < Element
  include ROXML


  xml_name "ns1:ReleaseDeal"

      xml_accessor :deal_release_references, :as => [], :from => "DealReleaseReference", :required => true
      xml_accessor :deals, :as => [DDEX::ERN::V41::Deal], :from => "Deal", :required => true


  

end

end end end
