#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:57 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/proprietary_id"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::ResourceProprietaryId < Element
  include ROXML


  xml_name "ns1:ResourceProprietaryId"

      xml_accessor :proprietary_ids, :as => [DDEX::ERN::V41::ProprietaryId], :from => "ProprietaryId", :required => true


  
      xml_accessor :replaced?, :from => "@IsReplaced", :required => false
    
  

end

end end end
