#
# Auto-generated by jaxb2ruby v0.0.1 on 2019-04-23 11:47:58 UTC
# https://github.com/sshaw/jaxb2ruby
#
#
# DO NOT MODIFY
# Automatically generated by jaxb2ruby v0.0.1 (https://github.com/sshaw/jaxb2ruby)
#

require "roxml"
require "ddex/element"

require "ddex/ern/v41/all_territory_code"

module DDEX module ERN module V41  # :nodoc: all

class DDEX::ERN::V41::WorkRightsController < Element
  include ROXML


  xml_name "ns1:WorkRightsController"

      xml_accessor :rights_controller_party_reference, :from => "RightsControllerPartyReference", :required => true
      xml_accessor :rights_controller_roles, :as => [], :from => "RightsControllerRole", :required => false
      xml_accessor :rights_controller_type, :from => "RightsControllerType", :required => false
      xml_accessor :right_share_percentage, :as => Float, :from => "RightSharePercentage", :required => false
      xml_accessor :right_share_unknown?, :from => "RightShareUnknown", :required => false
      xml_accessor :territories, :as => [DDEX::ERN::V41::AllTerritoryCode], :from => "Territory", :required => false
      xml_accessor :start_date, :from => "StartDate", :required => false
      xml_accessor :end_date, :from => "EndDate", :required => false


  

end

end end end
